name: Sync Repositories

on:
  push:
    branches:
      - main  # Déclencher ce workflow sur chaque push vers la branche `main` de mobifer

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout mobifer repository
      uses: actions/checkout@v3
      with:
        repository: Mobifer/mobifer
        token: ${{ secrets.GH_TOKEN }}
        ref: main  # Vérifier les fichiers sur la branche principale de mobifer

    - name: Clone mobifer.github.io repository
      run: |
        git clone --single-branch --branch main https://github.com/Mobifer/mobifer.github.io.git
        git clone --single-branch --branch main https://github.com/Mobifer/mobifer.git

    - name: Copy files from mobifer to mobifer.github.io
      run: |
        # Copie tous les fichiers de mobifer dans la racine de mobifer.github.io
        cp -R mobifer/ mobifer.github.io/

    - name: Commit and push changes to mobifer.github.io
      run: |
        cd mobifer.github.io
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"
        git add .
        git commit -m "Sync changes from mobifer" || echo "No changes to commit"
        git push origin main  # Pousse les changements dans mobifer.github.io
