name: Sync to mobifer.github.io

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mobifer repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone mobifer.github.io repository
        run: |
          git clone --single-branch https://github.com/Mobifer/mobifer.github.io.git gh-pages

      - name: Copy files from mobifer to mobifer.github.io
        run: |
          cp -r * gh-pages/
        
      - name: Commit and push changes
        run: |
          cd gh-pages
          git add .
          git commit -m "Sync changes from mobifer"
          git push origin main  # ou la branche principale de mobifer.github.io
