name: Sync to mobifer.github.io

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout du repository mobifer
      - name: Checkout mobifer repository
        uses: actions/checkout@v2

      # Configure Git avec ton nom et ton email
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@example.com"

      # Clone le repository mobifer.github.io
      - name: Clone mobifer.github.io repository
        run: |
          git clone --single-branch https://github.com/Mobifer/mobifer.github.io.git gh-pages

      # Supprimer les fichiers existants dans gh-pages et y copier les fichiers de mobifer
      - name: Copy files from mobifer to mobifer.github.io
        run: |
          # Suppression des fichiers existants dans le dossier gh-pages
          rm -rf gh-pages/*  # Supprimer tout le contenu de gh-pages
          
          # Copier les fichiers du repository mobifer dans gh-pages sans inclure le dossier gh-pages lui-même
          rsync -av --exclude 'gh-pages' ./ gh-pages/

      # Commit et push les changements dans mobifer.github.io
      - name: Commit and push changes
        run: |
          cd gh-pages
          git add .
          git commit -m "Sync changes from mobifer"
          git push origin main  # ou la branche principale de mobifer.github.io
